<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \MiltonBayer\General\Block\Product\ProductList\Toolbar
 */
use MiltonBayer\General\Model\Product\ProductList\Toolbar;

$selected = 'selected="selected"';
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort By') ?></label>
    <select class="js-sort-select sorter-options">
        <?php foreach ($block->getAvailableOrderAndDirections() as $_key => $_order): ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>

    <a type="text" data-role="sorter" class="js-sort-field" data-value="special_price"></a>
    <a type="text" data-role="direction-switcher" class="js-sort-direction"></a>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "product_list_toolbar_sorter": {}
        }
    }
</script>
