<?php
/** @var \MiltonBayer\General\Block\Adminhtml\Category\AssignCrosssellProducts $block */

/** @var \Magento\Catalog\Block\Adminhtml\Category\Tab\Product $blockGrid */
$blockGrid = $block->getBlockGrid();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="crosssell_category_products" id="in_crosssell_category_products" data-form-part="category_form" value="" />
<!-- <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Catalog/catalog/category/assign-crosssell-products": {
            }
        }
    }
</script> -->
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
