<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
            </a>
        </li>
    <?php endforeach ?>
</ol>
