<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <?php $value = $filterItem->getValue(); ?>
        <li class="item <?= empty($selected) || !in_array($value, $selected) ? 'active' : '' ?>">
            <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                <?php $value = $filterItem->getValue(); ?>
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
            </a>
        </li>
    <?php endforeach ?>
</ol>


<style>
    ol.items li.item.active {
        background: #006bb4;
    }

    ol.items li.item.active a {
        color: #fff;
    }
</style>
