<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \MiltonBayer\General\Block\Navigation
 */
$selectedFilters = $block->getLayer()->getState()->getFilters();
$is_design_a_door = $block->getIsDesignADoor();

?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($selectedFilters) ?>
        <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */ $filtered ?>">
            <strong data-role="title"><?= /* @escapeNotVerified */ __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getRequestVar() !== 'manufacturer' && $filter->getRequestVar() !== 'cat' ): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= /* @escapeNotVerified */ __('Refine your search') ?></strong>
                    <?php  $wrapOptions = true; endif; ?>
                    <div class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?= /* @escapeNotVerified */ __($filter->getName()) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->renderOptions($filter, $selectedFilters, $is_design_a_door) ?></div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>

            <div class="block-actions filter-actions">
                <?php
                    if( $is_design_a_door ):
                        echo '<div class="action clear filter-clear js-filter-clear"><span>' . __('Clear All') . '</span></div>';
                    else:
                        echo '<a href="' . $block->getClearUrl() . '" class="action clear filter-clear ' . (count($selectedFilters) > 0 ?: 'disabled') . '"><span>' . __('Clear All') . '</span></a>';
                    endif;
                ?>
            </div>
            <?php if (!$wrapOptions): ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<?php if( $is_design_a_door ): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "category_filter": {}
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
        {
            ".js-items.js-price": {
                "price_filter": {}
            }
        }
    </script>
<?php endif; ?>
