<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($_description = $block->getCurrentCategory()->getDescription()): ?>
    <div class="category-description">
        <div class="js-category-description-wrapper">
            <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
        </div>

        <button class="js-category-description-toggle">More Info</button>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "category_description": {}
        }
    }
</script>
