<?php
/* @var $block \MiltonBayer\General\Block\Product\View\Options */
$_options = $block->decorateArray($block->getOptions());
$_productId = $block->getProduct()->getId();

if (count($_options)) {
?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "priceOptions": {
                    "optionConfig": <?= $block->getJsonConfig() ?>,
                    "controlContainer": ".field",
                    "priceHolderSelector": "[data-product-id='<?= $block->escapeHtml($_productId) ?>'][data-role=priceBox]"
                }
            }
        }
    </script>
<?php
    foreach ($_options as $_option) {
        if( $_option->getData('is_show_product_page') ) {
            echo $block->getOptionHtml($_option);
        }
    }
}
